Add JwtProperties @Bean to BeansApplication
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webSecurityConfig' defined in file [/Users/davidgrieser/work/cohorts/state-farm/c1/beans/out/production/classes/com/galvanize/beans/security/WebSecurityConfig.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.galvanize.beans.security.JwtProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.galvanize.beans.security.JwtProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}